name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Frontend Docker image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/chatui:v3" .

      - name: Push Frontend Docker image to Docker Hub
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/chatui:v3"

      - name: Build Backend Docker image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/chatback:v3" ./backend

      - name: Push Frontend Docker image to Docker Hub
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/chatback:v3"

      - name: Build Frontend
        working-directory: .
        run: |
          # Add commands to build the frontend project (replace with your build command)
          npm install
          npm run build

      - name: Build Backend
        working-directory: ./backend
        run: |
          npm install
          npm run build
